name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      - name: Package Application with PyInstaller
        run: |
          dir
          pyinstaller cs2chatbot.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-exe
          path: dist/cs2chatbot/cs2chatbot.exe
