name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download SQLite Amalgamation
        run: |
          curl -o sqlite.zip https://www.sqlite.org/2024/sqlite-amalgamation-3460100.zip
          unzip sqlite.zip
          mkdir sqlite
          mv sqlite-amalgamation-3460100/*.h sqlite/
          mv sqlite-amalgamation-3460100/*.c sqlite/
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Set include and lib paths for pysqlite3
          export CFLAGS="-I${{ github.workspace }}/sqlite"
          export LDFLAGS="-L${{ github.workspace }}/sqlite"
          pip install pysqlite3
          pip install -r requirements.txt --no-deps
        shell: bash

      - name: Package Application with PyInstaller
        run: |
          pyinstaller cs2chatbot.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-exe
          path: dist/cs2chatbot/cs2chatbot.exe
