name: Package Application with PyInstaller
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Download Visual C++ Redistributable DLLs
        run: |
          curl -o vcruntime140.dll https://aka.ms/vs/16/release/vcruntime140.dll -L
          curl -o msvcp140.dll https://aka.ms/vs/16/release/msvcp140.dll -L
          mkdir dlls
          move vcruntime140.dll dlls/
          move msvcp140.dll dlls/
        shell: cmd
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      - name: Package Application with PyInstaller
        run: |
          python --version
          pyinstaller --log-level DEBUG cs2chatbot.spec
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-exe
          path: dist/cs2chatbot/cs2chatbot.exe
